#include <libopencm3/stm32/rcc.h>
#include <libopencm3/stm32/gpio.h>
#include <libopencm3/stm32/timer.h>

int main(void)
{
    rcc_periph_clock_enable(RCC_GPIOC);
    rcc_periph_clock_enable(RCC_TIM3);

    // Setup GPIOC13 as alternate function (PWM)
    gpio_set_mode(GPIOC, GPIO_MODE_OUTPUT_50_MHZ, GPIO_CNF_OUTPUT_ALTFN_PUSHPULL, GPIO12);

    // Set the Timer mode to no divisor (72MHz), Edge-aligned, up-counting
    timer_set_mode(TIM3, TIM_CR1_CKD_CK_INT, TIM_CR1_CMS_EDGE, TIM_CR1_DIR_UP);

    // Set prescaler to 72, timer tick of 1us
    timer_set_prescaler(TIM3, 72);

    // Set the auto-reload value for 50% duty cycle
    timer_set_period(TIM3, 20000); // 20ms period for a 50Hz signal
    timer_set_oc_value(TIM3, TIM_OC4, 1500); // 1.5ms pulse for 7.5% duty cycle

    // Set output compare mode to PWM1 (active if count < compare)
    timer_set_oc_mode(TIM3, TIM_OC4, TIM_OCM_PWM1);
    timer_enable_oc_output(TIM3, TIM_OC4);

    // Start the timer
    timer_enable_counter(TIM3);

    while (1) {
        // Loop forever, the PWM signal is generated by the hardware
    }

    return 0;
}
